-- DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER (
    ID INTEGER NOT NULL IDENTITY,
    FNAME VARCHAR,
    LNAME VARCHAR,
    EMAIL VARCHAR,
    PHONENUMBER VARCHAR,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    VERSION INTEGER,
    PRIMARY KEY (ID)
);